### ISSUE TITLE
Make "hassio.local" variable

### ISSUE THREAD

**Issue by freemann** [kdw2060/hassio-custom-cards#2]
This plugin is working great on the HA, but I needed to change "hassio.local" manual to "xxx.xxx.xxx.xxx".
Maybe you could make the adr. configurable by a parameter in LoveLace?

**Comment by kdw2060** [comment]
Hi and sorry for not reacting quicker. That sounds like a good idea. I'll make the change once I've finished my other Home Assistant thingies that I'm working on (probably will take a while).

**Comment by kdw2060** [comment]
done
