### ISSUE TITLE
Card doesn't render correctly in Safari and IOS Companion App 2.0.0(69)

### ISSUE THREAD

**Issue by linuxius** [kdw2060/hassio-custom-cards#4]
First of all thanks for your great work on this cards. I looks great.

I renders fine on Chrome and Firefox, but is doesn't on Safari and the IOS which probably uses the same engine as Safari. The issue is that the little min/max triangles are not displayed correctly.

I assume is has something to do which Safari no handling the CCS code the right way. 

I have attached a screenshot.
![screenshot_barometer_ios](https://user-images.githubusercontent.com/33897272/73275646-bbaab880-41e7-11ea-8571-ba25dc324796.png)

Thanks for your support.

**Comment by kdw2060** [comment]
Hi, I changed those thingies to svg's, didn't test on Safari, but i guess that should fix it.
